// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: proto/vidsy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents status codes
type Status int32

const (
	Status_SUCCESS      Status = 0
	Status_FAILED       Status = 1
	Status_UNAUTHORIZED Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
		2: "UNAUTHORIZED",
	}
	Status_value = map[string]int32{
		"SUCCESS":      0,
		"FAILED":       1,
		"UNAUTHORIZED": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_vidsy_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_vidsy_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_vidsy_proto_rawDescGZIP(), []int{0}
}

// Different operations available
type OperationType int32

const (
	OperationType_TRIM          OperationType = 0
	OperationType_MERGE         OperationType = 1
	OperationType_BLUR          OperationType = 2
	OperationType_SCALE         OperationType = 3
	OperationType_BW            OperationType = 4
	OperationType_REMOVE_AUDIO  OperationType = 5
	OperationType_ADD_AUDIO     OperationType = 6
	OperationType_EXTRACT_AUDIO OperationType = 7
	OperationType_IMAGES        OperationType = 8
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "TRIM",
		1: "MERGE",
		2: "BLUR",
		3: "SCALE",
		4: "BW",
		5: "REMOVE_AUDIO",
		6: "ADD_AUDIO",
		7: "EXTRACT_AUDIO",
		8: "IMAGES",
	}
	OperationType_value = map[string]int32{
		"TRIM":          0,
		"MERGE":         1,
		"BLUR":          2,
		"SCALE":         3,
		"BW":            4,
		"REMOVE_AUDIO":  5,
		"ADD_AUDIO":     6,
		"EXTRACT_AUDIO": 7,
		"IMAGES":        8,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_vidsy_proto_enumTypes[1].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_vidsy_proto_enumTypes[1]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_vidsy_proto_rawDescGZIP(), []int{1}
}

// A Response to be sent back
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  Status `protobuf:"varint,1,opt,name=status,proto3,enum=vidsy.Status" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpPath  string `protobuf:"bytes,3,opt,name=up_path,json=upPath,proto3" json:"up_path,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vidsy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vidsy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_vidsy_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_SUCCESS
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetUpPath() string {
	if x != nil {
		return x.UpPath
	}
	return ""
}

// An entire operation with its params
type Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type OperationType `protobuf:"varint,1,opt,name=type,proto3,enum=vidsy.OperationType" json:"type,omitempty"`
	// Types that are assignable to Params:
	//	*Operation_Trim
	Params isOperation_Params `protobuf_oneof:"params"`
}

func (x *Operation) Reset() {
	*x = Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vidsy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vidsy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_proto_vidsy_proto_rawDescGZIP(), []int{1}
}

func (x *Operation) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_TRIM
}

func (m *Operation) GetParams() isOperation_Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (x *Operation) GetTrim() *TrimParams {
	if x, ok := x.GetParams().(*Operation_Trim); ok {
		return x.Trim
	}
	return nil
}

type isOperation_Params interface {
	isOperation_Params()
}

type Operation_Trim struct {
	Trim *TrimParams `protobuf:"bytes,2,opt,name=trim,proto3,oneof"`
}

func (*Operation_Trim) isOperation_Params() {}

// A request
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownPath   string       `protobuf:"bytes,1,opt,name=down_path,json=downPath,proto3" json:"down_path,omitempty"`
	Operations []*Operation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vidsy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vidsy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_vidsy_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetDownPath() string {
	if x != nil {
		return x.DownPath
	}
	return ""
}

func (x *Request) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

// Trim request params
type TrimParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int32 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End   int32 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *TrimParams) Reset() {
	*x = TrimParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vidsy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrimParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimParams) ProtoMessage() {}

func (x *TrimParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vidsy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimParams.ProtoReflect.Descriptor instead.
func (*TrimParams) Descriptor() ([]byte, []int) {
	return file_proto_vidsy_proto_rawDescGZIP(), []int{3}
}

func (x *TrimParams) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TrimParams) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_proto_vidsy_proto protoreflect.FileDescriptor

var file_proto_vidsy_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x69, 0x64, 0x73, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76, 0x69, 0x64, 0x73, 0x79, 0x22, 0x64, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x76, 0x69, 0x64, 0x73, 0x79, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x70, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x70, 0x50, 0x61, 0x74, 0x68,
	0x22, 0x68, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x76, 0x69,
	0x64, 0x73, 0x79, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x72, 0x69, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x69, 0x64, 0x73, 0x79, 0x2e, 0x54, 0x72,
	0x69, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x04, 0x74, 0x72, 0x69, 0x6d,
	0x42, 0x08, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x58, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x30, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x69, 0x64, 0x73, 0x79, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x34, 0x0a, 0x0a, 0x54, 0x72, 0x69, 0x6d, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x2a, 0x33, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x02, 0x2a,
	0x81, 0x01, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x52, 0x49, 0x4d, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4d,
	0x45, 0x52, 0x47, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4c, 0x55, 0x52, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x53, 0x43, 0x41, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x42,
	0x57, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x41, 0x55,
	0x44, 0x49, 0x4f, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x44, 0x44, 0x5f, 0x41, 0x55, 0x44,
	0x49, 0x4f, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x58, 0x54, 0x52, 0x41, 0x43, 0x54, 0x5f,
	0x41, 0x55, 0x44, 0x49, 0x4f, 0x10, 0x07, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4d, 0x41, 0x47, 0x45,
	0x53, 0x10, 0x08, 0x32, 0x32, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x73, 0x79, 0x12, 0x29, 0x0a, 0x04,
	0x45, 0x64, 0x69, 0x74, 0x12, 0x0e, 0x2e, 0x76, 0x69, 0x64, 0x73, 0x79, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x76, 0x69, 0x64, 0x73, 0x79, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x6f, 0x76, 0x41, 0x68, 0x31, 0x33, 0x68, 0x2f, 0x56,
	0x69, 0x64, 0x73, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_vidsy_proto_rawDescOnce sync.Once
	file_proto_vidsy_proto_rawDescData = file_proto_vidsy_proto_rawDesc
)

func file_proto_vidsy_proto_rawDescGZIP() []byte {
	file_proto_vidsy_proto_rawDescOnce.Do(func() {
		file_proto_vidsy_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_vidsy_proto_rawDescData)
	})
	return file_proto_vidsy_proto_rawDescData
}

var file_proto_vidsy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_vidsy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_vidsy_proto_goTypes = []interface{}{
	(Status)(0),        // 0: vidsy.Status
	(OperationType)(0), // 1: vidsy.OperationType
	(*Response)(nil),   // 2: vidsy.Response
	(*Operation)(nil),  // 3: vidsy.Operation
	(*Request)(nil),    // 4: vidsy.Request
	(*TrimParams)(nil), // 5: vidsy.TrimParams
}
var file_proto_vidsy_proto_depIdxs = []int32{
	0, // 0: vidsy.Response.status:type_name -> vidsy.Status
	1, // 1: vidsy.Operation.type:type_name -> vidsy.OperationType
	5, // 2: vidsy.Operation.trim:type_name -> vidsy.TrimParams
	3, // 3: vidsy.Request.operations:type_name -> vidsy.Operation
	4, // 4: vidsy.Vidsy.Edit:input_type -> vidsy.Request
	2, // 5: vidsy.Vidsy.Edit:output_type -> vidsy.Response
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_vidsy_proto_init() }
func file_proto_vidsy_proto_init() {
	if File_proto_vidsy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_vidsy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vidsy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vidsy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vidsy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrimParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_vidsy_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Operation_Trim)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_vidsy_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vidsy_proto_goTypes,
		DependencyIndexes: file_proto_vidsy_proto_depIdxs,
		EnumInfos:         file_proto_vidsy_proto_enumTypes,
		MessageInfos:      file_proto_vidsy_proto_msgTypes,
	}.Build()
	File_proto_vidsy_proto = out.File
	file_proto_vidsy_proto_rawDesc = nil
	file_proto_vidsy_proto_goTypes = nil
	file_proto_vidsy_proto_depIdxs = nil
}
